INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00233','Joao Geraldo da Fonseca',TO_DATE('01/12/2015', 'DD/MM/YYYY'), 0.10);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00400','Maria do Rosario',TO_DATE('23/07/2012', 'DD/MM/YYYY'), 0.15);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00810','Marcia Almeida',TO_DATE('14/12/2016', 'DD/MM/YYYY'), 0.18);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00414','Carlos Moreira',TO_DATE('13/11/2015', 'DD/MM/YYYY'), 0.14);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00934','Juvenildo Martins',TO_DATE('09/03/2010', 'DD/MM/YYYY'), 0.20);

SELECT * FROM TB_VENDEDORES;

UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.18;
UPDATE TB_VENDEDORES SET PERCENTUAL_COMISSAO = 0.20 WHERE MATRICULA = '00934';

DELETE FROM TB_VENDEDORES WHERE MATRICULA = '00400';

ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY (MATRICULA);
DESC TB_VENDEDORES;

--INCLUSÃO DE 2 VENDEDORES AMERICANOS E 2 BRASILEIROS
INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00265','Jonh Wayne',TO_DATE('03/27/2019', 'MM/DD/YYYY'), 0.12);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00777','Katy Peterson',TO_DATE('02/04/2020', 'MM/DD/YYYY'), 0.10);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00342','Rodrigo Almeida',TO_DATE('18/01/2022', 'DD/MM/YYYY'), 0.09);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO) VALUES
('00729','Patricia Martins',TO_DATE('02/01/2022', 'DD/MM/YYYY'), 0.09);