SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES ('1040107', 'Light - 350 ml - Melancia','Lata','350 ml','Melancia', 4.56);

SELECT * FROM TB_CLIENTES;



SELECT * FROM TB_VENDEDORES;
DELETE FROM TB_VENDEDORES;

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00233', 'Joao Geraldo da Fonseca',TO_DATE('01/12/2015', 'MM/DD/YYYY'), 10);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00400', 'Maria do Rosario',TO_DATE('27/03/2012', 'MM/DD/YYYY'), 15);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00810', 'Marcia Almeida',TO_DATE('12/14/2016', 'MM/DD/YYYY'), 18);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00414', 'Carlos Moreira',TO_DATE('13/11/2015', 'DD//YYYY'), 14);

INSERT INTO TB_VENDEDORES (MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES ('00934', 'Junvenildo Martins',TO_DATE('09/03/2010', 'MM/DD/YYYY'), 20);




