SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;

SELECT * FROM TB_CLIENTES WHERE NOME > 'Marcelo Mattos';

SELECT * FROM TB_CLIENTES WHERE NOME <> 'Marcelo Mattos';

SELECT * FROM TB_CLIENTES WHERE (IDADE >= 18 AND SEXO = 'F') AND (CIDADE = 'Sao Paulo' OR BAIRRO = 'Barra da Tijuca');

SELECT * FROM TB_CLIENTES WHERE (IDADE >= 18 AND SEXO = 'F' AND CIDADE = 'Sao Paulo') OR BAIRRO = 'Barra da Tijuca';

SELECT 
    NOME,
    ENDERECO1 || ', ' || BAIRRO || ', ' || CIDADE || ' - ' || ESTADO AS "ENDEREÇO COMPLETO"
FROM  TB_CLIENTES;