DESC TB_PRODUTOS;

CREATE TABLE TB_PRODUTOS (
    PRODUTO           VARCHAR2(20),
    NOME              VARCHAR2(150),
    EMBALAGEM         VARCHAR2(50),
    TAMANHO           VARCHAR2(50),
    SABOR             VARCHAR2(50),
    PRECO_LISTA       NUMBER
);
SELECT * FROM TB_PRODUTOS;


CREATE TABLE TB_PRODUTOS2 (
    PRODUTO           VARCHAR2(20),
    NOME              VARCHAR2(150),
    EMBALAGEM         VARCHAR2(50),
    TAMANHO           VARCHAR2(50),
    SABOR             VARCHAR2(50),
    PRECO_LISTA       NUMBER
);
SELECT * FROM TB_PRODUTOS2;
DROP TABLE TB_PRODUTOS2;

CREATE TABLE TB_PRODUTOS3 (
    PRODUTO           VARCHAR2(20),
    NOME              VARCHAR2(150),
    EMBALAGEM         VARCHAR2(50),
    TAMANHO           VARCHAR2(50),
    SABOR             VARCHAR2(50),
    PRECO_LISTA       NUMBER
);
SELECT * FROM TB_PRODUTOS3;
DROP TABLE TB_PRODUTOS3;


