SELECT * FROM TB_VENDEDORES;
DESC TB_VENDEDORES;

DELETE FROM TB_VENDEDORES;

CREATE TABLE TB_VENDEDORES (
    MATRICULA VARCHAR2(5),   
    NOME VARCHAR2(100),
    DATA_ADMISSAO DATE,          
    PERCENTUAL_COMISSAO NUMBER
);

DROP TABLE TB_VENDEDORES;


